/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppTitle: typeof import('./components/AppTitle.vue')['default']
    Auth: typeof import('./components/Auth.vue')['default']
    BlockEditor: typeof import('./components/BlockEditor.vue')['default']
    ChatContainer: typeof import('./components/ChatContainer.vue')['default']
    ChatInput: typeof import('./components/ChatInput.vue')['default']
    ChatList: typeof import('./components/ChatList.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    ChatView: typeof import('./components/ChatView.vue')['default']
    DataViz: typeof import('./components/DataViz.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    ProfileBox: typeof import('./components/ProfileBox.vue')['default']
    PubSub: typeof import('./components/PubSub.vue')['default']
    QueueFeed: typeof import('./components/QueueFeed.vue')['default']
    Raw: typeof import('./components/Raw.vue')['default']
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerEvent: typeof import('./components/ServerEvent.vue')['default']
    Thumbnail: typeof import('./components/Thumbnail.vue')['default']
    Tiptap: typeof import('./components/Tiptap.vue')['default']
    Uploadcsv: typeof import('./components/Uploadcsv.vue')['default']
    UploadPdf: typeof import('./components/UploadPdf.vue')['default']
    UploadZone: typeof import('./components/UploadZone.vue')['default']
    WebSocket: typeof import('./components/WebSocket.vue')['default']
    WordCloud: typeof import('./components/WordCloud.vue')['default']
  }
}
